# DATABASE CONFIG

spring:
  datasource:
    url: # your database url
    username: # your database username
    password: # your database password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

admin:
  super-admin:
    password: # your super admin password

springdoc:
  pathsToMatch: /api/v1/**
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs

jwt:
  secret:
    key: # your secret key: generate it at https://asecuritysite.com/encryption/plain
